;;; tip-spinner.el --- Animated spinner for TIP compilation -*- lexical-binding: t; -*-

;;; Commentary:
;; Displays a rotating Typst "t" logo in the mode line while the
;; tip-server is processing requests.  Spins when there are pending
;; callbacks, shows a static logo when idle.
;;
;; The 8 frames were generated by typst: white "t" in Libertinus Serif
;; on #239dad background, rotated 0-315 degrees in 45 degree steps.
;;
;; Usage:
;;   (add-hook 'typst-ts-mode-hook #'tip-spinner-setup)

;;; Code:

(defvar tip-spinner--frames nil
  "Vector of SVG strings for spinner animation frames.
Loaded lazily from spinner/*.svg files.")

(defvar-local tip-spinner--index 0
  "Current frame index.")

(defvar-local tip-spinner--timer nil
  "Timer that checks server status and updates animation.")

(defvar-local tip-spinner--mode-cookie nil
  "Mode-line entry managed by tip-spinner-mode.")

(defun tip-spinner--load-frames ()
  "Load spinner SVG frames from the spinner/ directory."
  (unless tip-spinner--frames
    (let* ((dir (expand-file-name "spinner"
                                   (file-name-directory
                                    (or load-file-name buffer-file-name
                                        (locate-library "tip-spinner")))))
           (files (and (file-directory-p dir)
                       (sort (directory-files dir t "^spinner-[0-9]+\\.svg$")
                             #'string<))))
      (when files
        (setq tip-spinner--frames
              (vconcat (mapcar (lambda (f)
                                 (with-temp-buffer
                                   (insert-file-contents f)
                                   (buffer-string)))
                               files))))))
  tip-spinner--frames)

(defun tip-spinner--image ()
  "Return the current spinner frame as a mode-line image spec."
  (let ((frames (tip-spinner--load-frames)))
    (when frames
      (propertize " "
                  'display
                  (list 'image
                        :type 'svg
                        :data (aref frames (% tip-spinner--index
                                             (length frames)))
                        :ascent 'center
                        :height (frame-char-height))))))

(defun tip-spinner--tick ()
  "Advance frame if server is busy, hold frame 0 if idle."
  (let ((busy (and (boundp 'tip--pending-callbacks)
                   tip--pending-callbacks
                   (> (hash-table-count tip--pending-callbacks) 0))))
    (if busy
        (setq tip-spinner--index (1+ tip-spinner--index))
      (setq tip-spinner--index 0)))
  (force-mode-line-update))

;;;###autoload
(define-minor-mode tip-spinner-mode
  "Show a Typst logo in the mode line.
Spins while tip-server is processing, static when idle."
  :init-value nil
  :lighter ""
  (if tip-spinner-mode
      (progn
        (tip-spinner--load-frames)
        (unless tip-spinner--mode-cookie
          (setq tip-spinner--mode-cookie
                '(:eval (or (and (fboundp 'tip-spinner--image)
                                 (tip-spinner--image))
                            "")))
          (push tip-spinner--mode-cookie mode-line-format))
        (unless tip-spinner--timer
          (setq tip-spinner--timer
                (run-with-timer 0 0.12 #'tip-spinner--tick))))
    (when tip-spinner--timer
      (cancel-timer tip-spinner--timer)
      (setq tip-spinner--timer nil))
    (when tip-spinner--mode-cookie
      (setq mode-line-format
            (delq tip-spinner--mode-cookie mode-line-format))
      (setq tip-spinner--mode-cookie nil))
    (force-mode-line-update)))

;;;###autoload
(defun tip-spinner-setup ()
  "Enable tip-spinner-mode in typst-ts-mode buffers.
Add to your config: (add-hook \\='typst-ts-mode-hook #\\='tip-spinner-setup)"
  (when (derived-mode-p 'typst-ts-mode)
    (tip-spinner-mode 1)))

(provide 'tip-spinner)

;;; tip-spinner.el ends here
