;;; tip-spinner.el --- Animated spinner for TIP compilation -*- lexical-binding: t; -*-

;;; Commentary:
;; Displays a rotating Typst "t" logo in the mode line during compilation.
;; The 8 frames were generated by typst: white "t" in Libertinus Serif
;; on #239dad background, rotated 0° through 315° in 45° steps.

;;; Code:

(defvar tip-spinner--frames nil
  "Vector of SVG strings for spinner animation frames.
Loaded lazily from spinner/*.svg files.")

(defvar-local tip-spinner--index 0
  "Current frame index.")

(defvar-local tip-spinner--timer nil
  "Animation timer.")

(defun tip-spinner--load-frames ()
  "Load spinner SVG frames from the spinner/ directory."
  (unless tip-spinner--frames
    (let* ((dir (expand-file-name "spinner"
                                   (file-name-directory
                                    (or load-file-name buffer-file-name
                                        (locate-library "tip-spinner")))))
           (files (and (file-directory-p dir)
                       (sort (directory-files dir t "^spinner-[0-9]+\\.svg$")
                             #'string<))))
      (when files
        (setq tip-spinner--frames
              (vconcat (mapcar (lambda (f)
                                 (with-temp-buffer
                                   (insert-file-contents f)
                                   (buffer-string)))
                               files))))))
  tip-spinner--frames)

(defun tip-spinner--image ()
  "Return the current spinner frame as a mode-line image spec."
  (let ((frames (tip-spinner--load-frames)))
    (when frames
      (propertize " "
                  'display
                  (list 'image
                        :type 'svg
                        :data (aref frames (% tip-spinner--index
                                             (length frames)))
                        :ascent 'center
                        :height (frame-char-height))))))

(defun tip-spinner-start ()
  "Start the spinner animation in the mode line."
  (setq tip-spinner--index 0)
  (unless tip-spinner--timer
    (setq tip-spinner--timer
          (run-with-timer 0 0.12
                          (lambda ()
                            (setq tip-spinner--index (1+ tip-spinner--index))
                            (force-mode-line-update))))))

(defun tip-spinner-stop ()
  "Stop the spinner animation."
  (when tip-spinner--timer
    (cancel-timer tip-spinner--timer)
    (setq tip-spinner--timer nil))
  (setq tip-spinner--index 0)
  (force-mode-line-update))

;;;###autoload
(defun tip-spinner-demo ()
  "Show the spinning Typst logo in the mode line for 5 seconds."
  (interactive)
  (tip-spinner--load-frames)
  (tip-spinner-start)
  (run-with-timer 5 nil #'tip-spinner-stop)
  (message "Spinning for 5 seconds..."))

(provide 'tip-spinner)

;;; tip-spinner.el ends here
