;;; tip-spinner.el --- Animated spinner for TIP compilation -*- lexical-binding: t; -*-

;;; Commentary:
;; Displays a rotating Typst "t" logo in the mode line during compilation.
;; The 8 frames were generated by typst: white "t" in Libertinus Serif
;; on #239dad background, rotated 0° through 315° in 45° steps.

;;; Code:

(defvar tip-spinner--frames nil
  "Vector of SVG strings for spinner animation frames.
Loaded lazily from spinner/*.svg files.")

(defvar-local tip-spinner--index 0
  "Current frame index.")

(defvar-local tip-spinner--timer nil
  "Animation timer.")

(defun tip-spinner--load-frames ()
  "Load spinner SVG frames from the spinner/ directory."
  (unless tip-spinner--frames
    (let* ((dir (expand-file-name "spinner"
                                   (file-name-directory
                                    (or load-file-name buffer-file-name
                                        (locate-library "tip-spinner")))))
           (files (and (file-directory-p dir)
                       (sort (directory-files dir t "^spinner-[0-9]+\\.svg$")
                             #'string<))))
      (when files
        (setq tip-spinner--frames
              (vconcat (mapcar (lambda (f)
                                 (with-temp-buffer
                                   (insert-file-contents f)
                                   (buffer-string)))
                               files))))))
  tip-spinner--frames)

(defun tip-spinner--image ()
  "Return the current spinner frame as a mode-line image spec."
  (let ((frames (tip-spinner--load-frames)))
    (when frames
      (propertize " "
                  'display
                  (list 'image
                        :type 'svg
                        :data (aref frames (% tip-spinner--index
                                             (length frames)))
                        :ascent 'center
                        :height (frame-char-height))))))

(defun tip-spinner-start ()
  "Start the spinner animation in the mode line."
  (setq tip-spinner--index 0)
  (unless tip-spinner--timer
    (setq tip-spinner--timer
          (run-with-timer 0 0.12
                          (lambda ()
                            (setq tip-spinner--index (1+ tip-spinner--index))
                            (force-mode-line-update))))))

(defun tip-spinner-stop ()
  "Stop the spinner animation."
  (when tip-spinner--timer
    (cancel-timer tip-spinner--timer)
    (setq tip-spinner--timer nil))
  (setq tip-spinner--index 0)
  (force-mode-line-update))

(defvar-local tip-spinner--mode-cookie nil
  "Mode-line entry added by tip-spinner-mode.")

;;;###autoload
(define-minor-mode tip-spinner-mode
  "Persistent spinning Typst logo in the mode line."
  :init-value nil
  :lighter ""
  (if tip-spinner-mode
      (progn
        (tip-spinner--load-frames)
        (unless tip-spinner--mode-cookie
          (setq tip-spinner--mode-cookie
                '(:eval (or (and (fboundp 'tip-spinner--image)
                                 (tip-spinner--image))
                            "")))
          (push tip-spinner--mode-cookie mode-line-format))
        (tip-spinner-start))
    (tip-spinner-stop)
    (when tip-spinner--mode-cookie
      (setq mode-line-format
            (delq tip-spinner--mode-cookie mode-line-format))
      (setq tip-spinner--mode-cookie nil))))

;;;###autoload
(defun tip-spinner-demo ()
  "Spin the Typst logo for 5 seconds."
  (interactive)
  (tip-spinner-mode 1)
  (run-with-timer 5 nil
                  (lambda ()
                    (when tip-spinner-mode
                      (tip-spinner-mode -1))))
  (message "Spinning for 5 seconds..."))

;;;###autoload
(defun tip-spinner-setup ()
  "Enable tip-spinner-mode in typst-ts-mode buffers.
Add to your config: (add-hook \\='typst-ts-mode-hook #\\='tip-spinner-setup)"
  (when (derived-mode-p 'typst-ts-mode)
    (tip-spinner-mode 1)))

(provide 'tip-spinner)

;;; tip-spinner.el ends here
