(let ((base "/workspace/tip-repo/"))
  (add-to-list 'load-path base)
  (load (expand-file-name "tests/test-harness.el" base))
  (load (expand-file-name "tip.el" base)))

(test-harness-run
 "test-short-frags"
 (lambda ()
   (require 'package) (package-initialize) (require 'typst-ts-mode)
   (let ((file (make-temp-file "tip-short-" nil ".typ"))
         (p #'external-debugging-output))
     (find-file file)
     (insert "Text $a$ then $b$ then $g$ then $d$ end.\n")
     (save-buffer)
     (typst-ts-mode)
     (tip-mode 1)
     (tip-live-teardown)
     (sleep-for 1)
     (tip-render-all)
     (let ((deadline (+ (float-time) 10)))
       (while (and (< (float-time) deadline)
                   tip--server-process (process-live-p tip--server-process)
                   (> (hash-table-count tip--pending-callbacks) 0))
         (accept-process-output tip--server-process 0.1)
         (redisplay t)))

     (let ((ovs (length (seq-filter (lambda (ov) (and (eq (overlay-get ov 'tip) 'tip)
                                                      (overlay-get ov 'display)))
                                    (overlays-in (point-min) (point-max)))))
           (ranges (treesit-query-range 'typst "((math) @math)")))
       (print (format "overlays: %d fragments: %d" ovs (length ranges)) p)

       ;; Forward exit test
       (print "=== Forward exit ===" p)
       (dolist (r ranges)
         (let ((inside (1+ (car r)))
               (after (min (1+ (cdr r)) (point-max))))
           ;; Go outside
           (let ((this-command 'forward-char)) (run-hooks 'pre-command-hook))
           (goto-char (point-min))
           (let ((this-command 'forward-char)) (run-hooks 'post-command-hook))
           (redisplay t)
           ;; Enter
           (let ((this-command 'forward-char)) (run-hooks 'pre-command-hook))
           (goto-char inside)
           (let ((this-command 'forward-char)) (run-hooks 'post-command-hook))
           (redisplay t)
           ;; Leave forward
           (let ((this-command 'forward-char)) (run-hooks 'pre-command-hook))
           (goto-char after)
           (let ((this-command 'forward-char)) (run-hooks 'post-command-hook))
           (redisplay t)
           ;; Drain — recompile is async
           (let ((deadline (+ (float-time) 3)))
             (while (and (< (float-time) deadline)
                         tip--server-process (process-live-p tip--server-process)
                         (> (hash-table-count tip--pending-callbacks) 0))
               (accept-process-output tip--server-process 0.1)
               (redisplay t)))
           ;; Check
           (let ((closed (seq-find (lambda (ov) (and (eq (overlay-get ov 'tip) 'tip)
                                                     (overlay-get ov 'display)))
                                   (overlays-at inside))))
             (print (format "  %S: %s" r (if closed "OK" "FAIL")) p))))

       ;; Backward exit test
       (print "=== Backward exit ===" p)
       (dolist (r ranges)
         (let ((inside (1+ (car r)))
               (before (max (1- (car r)) (point-min))))
           (let ((this-command 'forward-char)) (run-hooks 'pre-command-hook))
           (goto-char (point-max))
           (let ((this-command 'forward-char)) (run-hooks 'post-command-hook))
           (redisplay t)
           (let ((this-command 'backward-char)) (run-hooks 'pre-command-hook))
           (goto-char inside)
           (let ((this-command 'backward-char)) (run-hooks 'post-command-hook))
           (redisplay t)
           (let ((this-command 'backward-char)) (run-hooks 'pre-command-hook))
           (goto-char before)
           (let ((this-command 'backward-char)) (run-hooks 'post-command-hook))
           (redisplay t)
           (let ((deadline (+ (float-time) 3)))
             (while (and (< (float-time) deadline)
                         tip--server-process (process-live-p tip--server-process)
                         (> (hash-table-count tip--pending-callbacks) 0))
               (accept-process-output tip--server-process 0.1)
               (redisplay t)))
           (let ((closed (seq-find (lambda (ov) (and (eq (overlay-get ov 'tip) 'tip)
                                                     (overlay-get ov 'display)))
                                   (overlays-at inside))))
             (print (format "  %S: %s" r (if closed "OK" "FAIL")) p))))

       ;; Fragment-to-fragment jump
       (print "=== Fragment-to-fragment ===" p)
       (let ((prev-inside nil))
         (dolist (r ranges)
           (let ((inside (1+ (car r))))
             (let ((this-command 'forward-char)) (run-hooks 'pre-command-hook))
             (goto-char inside)
             (let ((this-command 'forward-char)) (run-hooks 'post-command-hook))
             (redisplay t)
             (let ((deadline (+ (float-time) 3)))
               (while (and (< (float-time) deadline)
                           tip--server-process (process-live-p tip--server-process)
                           (> (hash-table-count tip--pending-callbacks) 0))
                 (accept-process-output tip--server-process 0.1)
                 (redisplay t)))
             (when prev-inside
               (let ((closed (seq-find (lambda (ov) (and (eq (overlay-get ov 'tip) 'tip)
                                                         (overlay-get ov 'display)))
                                       (overlays-at prev-inside))))
                 (print (format "  prev@%d: %s" prev-inside (if closed "OK" "FAIL")) p)))
             (setq prev-inside inside)))))

     (when tip--server-process (tip-shutdown))
     (sleep-for 0.3)
     (kill-buffer)
     (delete-file file))))
