/// Generate a baseline-diagram.typ with exact measurements from the frame tree,
/// then compile it to PDF with `typst compile`.
///
/// Run: cargo test -p tip-core-typst --test baseline_measure -- --nocapture
use std::fmt::Write as FmtWrite;
use std::io::Write;
use tip_core_typst::world::TipWorld;

fn measure_text_items(
    frame: &typst::layout::Frame,
    x_offset: f64,
    y_offset: f64,
    items: &mut Vec<(String, f64, f64, f64)>,
) {
    for (pos, item) in frame.items() {
        let ix = x_offset + pos.x.to_pt();
        let iy = y_offset + pos.y.to_pt();
        match item {
            typst::layout::FrameItem::Text(t) => {
                items.push((t.text.to_string(), ix, iy, t.size.to_pt()));
            }
            typst::layout::FrameItem::Group(g) => {
                measure_text_items(&g.frame, ix, iy, items);
            }
            _ => {}
        }
    }
}

fn measure_shapes(
    frame: &typst::layout::Frame,
    x_offset: f64,
    y_offset: f64,
    shapes: &mut Vec<(f64, f64)>,
) {
    for (pos, item) in frame.items() {
        let ix = x_offset + pos.x.to_pt();
        let iy = y_offset + pos.y.to_pt();
        match item {
            typst::layout::FrameItem::Shape(_, _) => shapes.push((ix, iy)),
            typst::layout::FrameItem::Group(g) => {
                measure_shapes(&g.frame, ix, iy, shapes);
            }
            _ => {}
        }
    }
}

fn find_group_baseline(frame: &typst::layout::Frame, y_offset: f64) -> Option<f64> {
    for (pos, item) in frame.items() {
        if let typst::layout::FrameItem::Group(g) = item {
            let gy = y_offset + pos.y.to_pt();
            if g.frame.has_baseline() {
                return Some(gy + g.frame.baseline().to_pt());
            }
            if let Some(bl) = find_group_baseline(&g.frame, gy) {
                return Some(bl);
            }
        }
    }
    None
}

struct Measurements {
    #[allow(dead_code)]
    page_w: f64,
    page_h: f64,
    items: Vec<(String, f64, f64, f64)>,
    #[allow(dead_code)]
    shapes: Vec<(f64, f64)>,
    group_baseline: Option<f64>,
}

fn compile_and_measure(world: &mut TipWorld, source: &str) -> Measurements {
    world.set_main_source(source);
    let warned = typst::compile::<typst::layout::PagedDocument>(world);
    let doc = warned.output.expect("compilation failed");
    let page = &doc.pages[0];
    let mut items = Vec::new();
    let mut shapes = Vec::new();
    measure_text_items(&page.frame, 0.0, 0.0, &mut items);
    measure_shapes(&page.frame, 0.0, 0.0, &mut shapes);
    Measurements {
        page_w: page.frame.width().to_pt(),
        page_h: page.frame.height().to_pt(),
        items,
        shapes,
        group_baseline: find_group_baseline(&page.frame, 0.0),
    }
}

struct FontMetrics {
    ascent_pt: f64,
    descent_pt: f64,
    axis_pt: f64,
}

fn get_font_metrics(world: &mut TipWorld) -> FontMetrics {
    let source = "#set page(height: auto, width: auto, margin: 0pt, fill: none)\n$a$\n";
    world.set_main_source(source);
    let warned = typst::compile::<typst::layout::PagedDocument>(world);
    let doc = warned.output.unwrap();
    for (_pos, item) in doc.pages[0].frame.items() {
        if let typst::layout::FrameItem::Text(t) = item {
            let ttf = t.font.ttf();
            let em = ttf.units_per_em() as f64;
            let sz = t.size.to_pt();
            let axis = ttf.tables().math.as_ref()
                .and_then(|m| m.constants.as_ref())
                .map(|c| c.axis_height().value as f64 / em * sz)
                .unwrap_or(0.0);
            return FontMetrics {
                ascent_pt: ttf.ascender() as f64 / em * sz,
                descent_pt: ttf.descender() as f64 / em * sz,
                axis_pt: axis,
            };
        }
    }
    panic!("no text item found");
}

#[test]
fn generate_baseline_diagram() {
    let mut world = TipWorld::new();
    let metrics = get_font_metrics(&mut world);
    let margin = 20.0_f64;
    let preamble = format!(
        "#set page(height: auto, width: auto, margin: (top: {margin}pt, bottom: {margin}pt, rest: 0pt), fill: none)\n"
    );

    let simple = compile_and_measure(&mut world, &format!("{preamble}$a + b$\n"));
    let subscript = compile_and_measure(&mut world, &format!("{preamble}$a_b$\n"));
    let fraction = compile_and_measure(&mut world, &format!("{preamble}$frac(a, b)$\n"));
    let mixed = compile_and_measure(&mut world, &format!("{preamble}$a + frac(b, c) = d$\n"));
    let bracket = compile_and_measure(&mut world, &format!("{preamble}$lr([1 / q_(0)])$\n"));

    let baseline_y = simple.items[0].2;

    let mut typ = String::new();

    // --- Header ---
    writeln!(typ, "// AUTO-GENERATED by baseline_measure.rs — do not edit by hand").unwrap();
    writeln!(typ, "// Regenerate: cd tip-server && cargo test -p tip-core-typst --test baseline_measure -- --nocapture").unwrap();
    writeln!(typ, "").unwrap();
    writeln!(typ, "#set page(width: 18cm, height: auto, margin: 1cm)").unwrap();
    writeln!(typ, "#set text(size: 11pt)").unwrap();
    writeln!(typ, "#import \"@preview/cetz:0.3.4\"").unwrap();
    writeln!(typ, "").unwrap();
    writeln!(typ, "= Baseline and Math Layout — Measured Diagrams").unwrap();
    writeln!(typ, "").unwrap();
    writeln!(typ, "All positions extracted from Typst's frame tree (New Computer Modern Math, 11pt).").unwrap();
    writeln!(typ, "Math expressions rendered as single Typst blocks — Typst handles all internal layout.").unwrap();
    writeln!(typ, "Reference lines drawn at measured positions using the same coordinate scale.").unwrap();
    writeln!(typ, "").unwrap();

    // --- Font metrics table ---
    writeln!(typ, "== Font Metrics").unwrap();
    writeln!(typ, "").unwrap();
    writeln!(typ, "#table(").unwrap();
    writeln!(typ, "  columns: (auto, auto, auto),").unwrap();
    writeln!(typ, "  stroke: 0.5pt, inset: 8pt,").unwrap();
    writeln!(typ, "  [*Metric*], [*Value*], [*Meaning*],").unwrap();
    writeln!(typ, "  [font ascent], [{:.2}pt], [top of tallest glyph above baseline],", metrics.ascent_pt).unwrap();
    writeln!(typ, "  [font descent], [{:.2}pt], [bottom of deepest glyph below baseline],", metrics.descent_pt).unwrap();
    writeln!(typ, "  [math axis], [{:.2}pt], [center of $+$, $=$, fraction bars — above baseline],", metrics.axis_pt).unwrap();
    writeln!(typ, "  [baseline y], [{:.2}pt], [{:.0}pt margin $+$ {:.2}pt ascent from page top],", baseline_y, margin, metrics.ascent_pt).unwrap();
    writeln!(typ, ")").unwrap();
    writeln!(typ, "").unwrap();

    // =======================================================================
    // DIAGRAM 1: Text anatomy
    //
    // Strategy: use `length: 3pt` so 1 CeTZ unit = 3pt on page.
    // Render text at 33pt (11pt × 3) so glyph proportions match the
    // reference lines. Place math as a single expression.
    // Baseline at y=0, ascent positive (up), descent negative (down).
    // =======================================================================
    let k = 3.0_f64; // magnification factor
    let text_size = 11.0 * k; // displayed text size in pt
    let line_w = 150.0_f64; // line width in CeTZ units (= 150 * 3 = 450pt on page)

    writeln!(typ, "== Diagram 1: Baseline, Ascent, Descent, Math Axis").unwrap();
    writeln!(typ, "").unwrap();

    writeln!(typ, "#cetz.canvas(length: {k}pt, {{").unwrap();
    writeln!(typ, "  import cetz.draw: *").unwrap();

    // Background
    writeln!(typ, "  rect((-8, {:.2}), ({:.0}, {:.2}), fill: rgb(\"#f8f8f8\"), stroke: none)",
        metrics.descent_pt - 2.0, line_w, metrics.ascent_pt + 3.0).unwrap();

    // Baseline (red)
    writeln!(typ, "  line((-4, 0), ({:.0}, 0), stroke: (paint: red, thickness: 1.5pt))", line_w).unwrap();
    writeln!(typ, "  content(({:.0}, 0), anchor: \"west\", text(fill: red, weight: \"bold\", size: 9pt)[ baseline])", line_w).unwrap();

    // Ascent (blue dashed)
    writeln!(typ, "  line((-4, {a:.2}), ({w:.0}, {a:.2}), stroke: (paint: blue, thickness: 0.7pt, dash: \"dashed\"))",
        a = metrics.ascent_pt, w = line_w).unwrap();
    writeln!(typ, "  content(({:.0}, {:.2}), anchor: \"west\", text(fill: blue, size: 8pt)[ ascent ({:.2}pt)])",
        line_w, metrics.ascent_pt, metrics.ascent_pt).unwrap();

    // Descent (green dashed)
    writeln!(typ, "  line((-4, {d:.2}), ({w:.0}, {d:.2}), stroke: (paint: green.darken(20%), thickness: 0.7pt, dash: \"dashed\"))",
        d = metrics.descent_pt, w = line_w).unwrap();
    writeln!(typ, "  content(({:.0}, {:.2}), anchor: \"west\", text(fill: green.darken(20%), size: 8pt)[ descent ({:.2}pt)])",
        line_w, metrics.descent_pt, metrics.descent_pt).unwrap();

    // Math axis (orange dash-dotted) — only on the math side
    writeln!(typ, "  line((55, {a:.2}), ({w:.0}, {a:.2}), stroke: (paint: orange, thickness: 0.7pt, dash: \"dash-dotted\"))",
        a = metrics.axis_pt, w = line_w).unwrap();
    writeln!(typ, "  content(({:.0}, {:.2}), anchor: \"west\", text(fill: orange, size: 8pt)[ math axis ({:.2}pt)])",
        line_w, metrics.axis_pt, metrics.axis_pt).unwrap();

    // Text "Hbdpgy" — single content, baseline at y=0
    writeln!(typ, "  content((0, 0), anchor: \"base-west\", text(size: {text_size:.0}pt, font: \"New Computer Modern\")[Hbdpgy])").unwrap();

    // Math $a + frac(b,c) = d$ — single expression, baseline at y=0
    // Typst handles all internal layout (fraction bar, numerator, denominator)
    writeln!(typ, "  content((60, 0), anchor: \"base-west\", text(size: {text_size:.0}pt)[$a + frac(b, c) = d$])").unwrap();

    // Dimension arrows
    writeln!(typ, "  line((-6, 0), (-6, {:.2}), stroke: (paint: blue, thickness: 0.5pt), mark: (end: \">\", fill: blue))", metrics.ascent_pt).unwrap();
    writeln!(typ, "  line((-6, {:.2}), (-6, 0), stroke: (paint: blue, thickness: 0.5pt), mark: (end: \">\", fill: blue))", metrics.ascent_pt).unwrap();
    writeln!(typ, "  line((-6, 0), (-6, {:.2}), stroke: (paint: green.darken(20%), thickness: 0.5pt), mark: (end: \">\", fill: green.darken(20%)))", metrics.descent_pt).unwrap();
    writeln!(typ, "  line((-6, {:.2}), (-6, 0), stroke: (paint: green.darken(20%), thickness: 0.5pt), mark: (end: \">\", fill: green.darken(20%)))", metrics.descent_pt).unwrap();

    writeln!(typ, "}})").unwrap();
    writeln!(typ, "").unwrap();

    // =======================================================================
    // DIAGRAM 2: TIP's cropping pipeline
    // =======================================================================
    writeln!(typ, "== Diagram 2: TIP's Render → Crop Pipeline").unwrap();
    writeln!(typ, "").unwrap();
    writeln!(typ, "Full page with {:.0}pt margins. Baseline at {:.2}pt from top.", margin, baseline_y).unwrap();
    writeln!(typ, "TIP crops the SVG to the ink region (yellow), then computes ascent \\% for Emacs.").unwrap();
    writeln!(typ, "").unwrap();

    // Use 1pt scale for precision, show the actual page
    let ps = 0.12_f64; // cm per pt for this diagram
    let ph = mixed.page_h;

    // Use actual bbox for ink bounds
    let ink_top = mixed.items.iter().map(|i| i.2 - i.3 * 0.8).fold(f64::MAX, f64::min);
    let ink_bottom = mixed.items.iter().map(|i| i.2 + i.3 * 0.3).fold(f64::MIN, f64::max);
    let pad = 0.5;
    let crop_top = (ink_top - pad).max(0.0);
    let crop_bottom = (ink_bottom + pad).min(ph);
    let bic = baseline_y - crop_top;
    let depth = crop_bottom - baseline_y;

    // Convert page-y (y-down) to CeTZ-y (y-up): cy = (page_h - page_y) * ps
    let cy = |page_y: f64| -> f64 { (ph - page_y) * ps };
    let pw = 8.0_f64; // diagram width in cm

    writeln!(typ, "#cetz.canvas(length: 1cm, {{").unwrap();
    writeln!(typ, "  import cetz.draw: *").unwrap();

    // Page outline
    writeln!(typ, "  rect((0, 0), ({pw:.1}, {:.3}), fill: rgb(\"#f0f0f0\"), stroke: 0.5pt)", cy(0.0)).unwrap();

    // Top margin
    writeln!(typ, "  rect((0, {:.3}), ({pw:.1}, {:.3}), fill: rgb(\"#e8e8e8\"), stroke: none)",
        cy(margin), cy(0.0)).unwrap();
    writeln!(typ, "  content(({:.1}, {:.3}), anchor: \"west\", text(size: 7pt, fill: gray)[ {:.0}pt margin])",
        pw, (cy(0.0) + cy(margin)) / 2.0, margin).unwrap();

    // Bottom margin
    writeln!(typ, "  rect((0, 0), ({pw:.1}, {:.3}), fill: rgb(\"#e8e8e8\"), stroke: none)",
        cy(ph - margin)).unwrap();
    writeln!(typ, "  content(({:.1}, {:.3}), anchor: \"west\", text(size: 7pt, fill: gray)[ {:.0}pt margin])",
        pw, cy(ph - margin) / 2.0, margin).unwrap();

    // Ink region (yellow)
    writeln!(typ, "  rect((0.3, {:.3}), ({:.1}, {:.3}), fill: rgb(\"#fff3cd\"), stroke: (paint: orange, thickness: 0.5pt, dash: \"dashed\"))",
        cy(ink_bottom), pw - 0.3, cy(ink_top)).unwrap();

    // Math expression centered
    writeln!(typ, "  content(({:.1}, {:.3}), anchor: \"base\", text(size: 11pt)[$a + frac(b, c) = d$])",
        pw / 2.0, cy(baseline_y)).unwrap();

    // Baseline
    writeln!(typ, "  line((0, {bl:.3}), ({pw:.1}, {bl:.3}), stroke: (paint: red, thickness: 1pt))",
        bl = cy(baseline_y)).unwrap();
    writeln!(typ, "  content(({:.1}, {:.3}), anchor: \"west\", text(fill: red, size: 8pt)[ baseline ({:.2}pt)])",
        pw, cy(baseline_y), baseline_y).unwrap();

    // Crop lines (blue dashed)
    writeln!(typ, "  line((-0.2, {:.3}), ({:.1}, {:.3}), stroke: (paint: blue, thickness: 0.7pt, dash: \"dashed\"))",
        cy(crop_top), pw + 0.1, cy(crop_top)).unwrap();
    writeln!(typ, "  line((-0.2, {:.3}), ({:.1}, {:.3}), stroke: (paint: blue, thickness: 0.7pt, dash: \"dashed\"))",
        cy(crop_bottom), pw + 0.1, cy(crop_bottom)).unwrap();
    writeln!(typ, "  content((-0.5, {:.3}), anchor: \"east\", text(fill: blue, size: 7pt)[crop])",
        (cy(crop_top) + cy(crop_bottom)) / 2.0).unwrap();

    // baseline_in_crop arrow
    let ax = pw + 1.5;
    writeln!(typ, "  line(({ax:.1}, {:.3}), ({ax:.1}, {:.3}), stroke: (paint: red, thickness: 0.5pt), mark: (end: \">\", fill: red))",
        cy(crop_top), cy(baseline_y)).unwrap();
    writeln!(typ, "  line(({ax:.1}, {:.3}), ({ax:.1}, {:.3}), stroke: (paint: red, thickness: 0.5pt), mark: (end: \">\", fill: red))",
        cy(baseline_y), cy(crop_top)).unwrap();
    writeln!(typ, "  content(({:.1}, {:.3}), anchor: \"west\", text(fill: red, size: 7pt)[ {:.1}pt])",
        ax + 0.2, (cy(crop_top) + cy(baseline_y)) / 2.0, bic).unwrap();

    // depth arrow
    let dx = pw + 2.8;
    writeln!(typ, "  line(({dx:.1}, {:.3}), ({dx:.1}, {:.3}), stroke: (paint: green.darken(20%), thickness: 0.5pt), mark: (end: \">\", fill: green.darken(20%)))",
        cy(baseline_y), cy(crop_bottom)).unwrap();
    writeln!(typ, "  line(({dx:.1}, {:.3}), ({dx:.1}, {:.3}), stroke: (paint: green.darken(20%), thickness: 0.5pt), mark: (end: \">\", fill: green.darken(20%)))",
        cy(crop_bottom), cy(baseline_y)).unwrap();
    writeln!(typ, "  content(({:.1}, {:.3}), anchor: \"west\", text(fill: green.darken(20%), size: 7pt)[ depth {:.1}pt])",
        dx + 0.2, (cy(baseline_y) + cy(crop_bottom)) / 2.0, depth).unwrap();

    writeln!(typ, "}})").unwrap();
    writeln!(typ, "").unwrap();

    // =======================================================================
    // DIAGRAM 3: Fraction baseline via math axis
    //
    // Same strategy: single expression, `length: Kpt`, reference lines
    // at measured positions. Everything scales together.
    // =======================================================================
    writeln!(typ, "== Diagram 3: Fraction Bar on the Math Axis").unwrap();
    writeln!(typ, "").unwrap();

    let frac_num_y = fraction.items[0].2;
    let frac_den_y = fraction.items[1].2;
    let axis_page_y = baseline_y - metrics.axis_pt;

    writeln!(typ, "The fraction bar sits on the math axis ({:.2}pt above baseline).", metrics.axis_pt).unwrap();
    writeln!(typ, "Numerator baseline at {:.2}pt, denominator at {:.2}pt from page top.", frac_num_y, frac_den_y).unwrap();
    writeln!(typ, "Axis at {:.2}pt from page top.", axis_page_y).unwrap();
    writeln!(typ, "").unwrap();

    let k3 = 3.0_f64;
    let ts3 = 11.0 * k3;
    let lw3 = 120.0_f64;

    writeln!(typ, "#cetz.canvas(length: {k3}pt, {{").unwrap();
    writeln!(typ, "  import cetz.draw: *").unwrap();

    // Background
    writeln!(typ, "  rect((-8, {:.1}), ({:.0}, {:.1}), fill: rgb(\"#f8f8f8\"), stroke: none)",
        -8.0, lw3, metrics.ascent_pt + 3.0).unwrap();

    // Baseline (red)
    writeln!(typ, "  line((-4, 0), ({:.0}, 0), stroke: (paint: red, thickness: 1pt))", lw3).unwrap();
    writeln!(typ, "  content(({:.0}, 0), anchor: \"west\", text(fill: red, size: 8pt)[ baseline])", lw3).unwrap();

    // Math axis (orange)
    writeln!(typ, "  line((-4, {a:.2}), ({w:.0}, {a:.2}), stroke: (paint: orange, thickness: 0.7pt, dash: \"dash-dotted\"))",
        a = metrics.axis_pt, w = lw3).unwrap();
    writeln!(typ, "  content(({:.0}, {:.2}), anchor: \"west\", text(fill: orange, size: 8pt)[ axis ({:.2}pt)])",
        lw3, metrics.axis_pt, metrics.axis_pt).unwrap();

    // The expression — single block, Typst handles layout
    writeln!(typ, "  content((0, 0), anchor: \"base-west\", text(size: {ts3:.0}pt)[$a + frac(b, c) = d$])").unwrap();

    // Axis height arrow
    writeln!(typ, "  line((-6, 0), (-6, {:.2}), stroke: (paint: orange, thickness: 0.5pt), mark: (end: \">\", fill: orange))", metrics.axis_pt).unwrap();
    writeln!(typ, "  line((-6, {:.2}), (-6, 0), stroke: (paint: orange, thickness: 0.5pt), mark: (end: \">\", fill: orange))", metrics.axis_pt).unwrap();
    writeln!(typ, "  content((-8, {:.2}), anchor: \"east\", text(fill: orange, size: 7pt)[{:.2}pt])",
        metrics.axis_pt / 2.0, metrics.axis_pt).unwrap();

    writeln!(typ, "}})").unwrap();
    writeln!(typ, "").unwrap();

    // =======================================================================
    // DIAGRAM 4: Gallery — all expression types with overlay lines
    //
    // Each expression rendered at 3x with ascent/axis/baseline/descent overlays.
    // Two fonts: New Computer Modern Math (default) and Pennstander Math.
    // =======================================================================
    writeln!(typ, "#pagebreak()").unwrap();
    writeln!(typ, "== Diagram 4: Gallery of Inline Math with Overlays").unwrap();
    writeln!(typ, "").unwrap();
    writeln!(typ, "Each expression at 33pt (3× magnification). Overlay lines:").unwrap();
    writeln!(typ, "#text(fill: blue)[--- ascent] #h(1em)").unwrap();
    writeln!(typ, "#text(fill: orange)[-·- axis] #h(1em)").unwrap();
    writeln!(typ, "#text(fill: red)[— baseline] #h(1em)").unwrap();
    writeln!(typ, "#text(fill: green.darken(20%))[--- descent]").unwrap();
    writeln!(typ, "").unwrap();

    // Gallery entries: (label, typst_source, has_group)
    let gallery = [
        ("simple", "$a + b$"),
        ("subscript", "$a_b$"),
        ("superscript", "$a^2$"),
        ("sub+super", "$a_i^2$"),
        ("fraction", "$frac(a, b)$"),
        ("mixed", "$a + frac(b, c) = d$"),
        ("sqrt", "$sqrt(x)$"),
        ("nested sqrt", "$sqrt(1 + sqrt(x))$"),
        ("sum", "$sum_(i=0)^n x_i$"),
        ("integral", "$integral_0^1 f(x) dif x$"),
        ("matrix", "$mat(1, 0; 0, 1)$"),
        ("bracket", "$lr([1 / q_(0)])$"),
        ("abs", "$abs(x + y)$"),
        ("floor", "$floor(x / 2)$"),
        ("accent", "$tilde(a) + hat(b)$"),
        ("cases", "$cases(x &\"if\" x>0, -x)$"),
        ("paren frac", "$(a+b)/(c+d)$"),
        ("product", "$product_(k=1)^n a_k$"),
    ];

    let font_dir = format!(
        "{}/.ref/Pennstander-ref/fonts/otf",
        env!("CARGO_MANIFEST_DIR").replace("/tip-server/crates/tip-core-typst", ""),
    );
    let penn_world = TipWorld::with_font_dirs(&[font_dir.as_str()]);
    let penn_metrics = {
        let mut w = TipWorld::with_font_dirs(&[font_dir.as_str()]);
        let source = "#set page(height: auto, width: auto, margin: 0pt, fill: none)\n#show math.equation: set text(font: \"Pennstander Math\")\n$a$\n";
        w.set_main_source(source);
        let warned = typst::compile::<typst::layout::PagedDocument>(&w);
        let doc = warned.output.unwrap();
        let mut fm = FontMetrics { ascent_pt: 0.0, descent_pt: 0.0, axis_pt: 0.0 };
        for (_pos, item) in doc.pages[0].frame.items() {
            if let typst::layout::FrameItem::Text(t) = item {
                let ttf = t.font.ttf();
                let em = ttf.units_per_em() as f64;
                let sz = t.size.to_pt();
                fm.ascent_pt = ttf.ascender() as f64 / em * sz;
                fm.descent_pt = ttf.descender() as f64 / em * sz;
                fm.axis_pt = ttf.tables().math.as_ref()
                    .and_then(|m| m.constants.as_ref())
                    .map(|c| c.axis_height().value as f64 / em * sz)
                    .unwrap_or(0.0);
                break;
            }
        }
        fm
    };
    drop(penn_world);

    let fonts: &[(&str, &str, &FontMetrics)] = &[
        ("New Computer Modern Math", "", &metrics),
        ("Pennstander Math", "#show math.equation: set text(font: \"Pennstander Math\")\n", &penn_metrics),
    ];

    for (fi, (font_name, font_preamble, fm)) in fonts.iter().enumerate() {
        if fi > 0 {
            writeln!(typ, "#pagebreak()").unwrap();
        }
        writeln!(typ, "=== {font_name}").unwrap();
        writeln!(typ, "").unwrap();
        writeln!(typ, "Ascent {:.2}pt, descent {:.2}pt, axis {:.2}pt.", fm.ascent_pt, fm.descent_pt, fm.axis_pt).unwrap();
        writeln!(typ, "").unwrap();

        let gk = 3.0_f64; // magnification
        let gts = 11.0 * gk; // text size

        for (gi, (label, expr)) in gallery.iter().enumerate() {
            // Page break every 9 entries to keep pages reasonable
            if gi > 0 && gi % 9 == 0 {
                writeln!(typ, "#pagebreak()").unwrap();
                writeln!(typ, "=== {font_name} (continued)").unwrap();
                writeln!(typ, "").unwrap();
            }
            // Measure to check for Group baseline
            let src = format!("{preamble}{font_preamble}{expr}\n");
            let m = compile_and_measure(&mut world, &src);
            let has_group = m.group_baseline.is_some();
            let group_tag = if has_group { " ✓ Group baseline" } else { "" };

            // Width of the expression — estimate from page width
            let expr_w_units = m.page_w / gk + 4.0; // in CeTZ units, with padding
            let line_w = expr_w_units.max(40.0); // minimum width for labels

            writeln!(typ, "").unwrap();
            writeln!(typ, "*{label}*: `{expr}`{group_tag}").unwrap();
            writeln!(typ, "").unwrap();
            writeln!(typ, "#cetz.canvas(length: {gk}pt, {{").unwrap();
            writeln!(typ, "  import cetz.draw: *").unwrap();

            // Background
            writeln!(typ, "  rect((-2, {:.2}), ({:.0}, {:.2}), fill: rgb(\"#fafafa\"), stroke: none)",
                fm.descent_pt - 1.0, line_w, fm.ascent_pt + 1.0).unwrap();

            // Ascent (blue dashed)
            writeln!(typ, "  line((-1, {a:.2}), ({w:.0}, {a:.2}), stroke: (paint: blue.lighten(40%), thickness: 0.5pt, dash: \"dashed\"))",
                a = fm.ascent_pt, w = line_w).unwrap();

            // Math axis (orange dash-dotted)
            writeln!(typ, "  line((-1, {a:.2}), ({w:.0}, {a:.2}), stroke: (paint: orange.lighten(30%), thickness: 0.5pt, dash: \"dash-dotted\"))",
                a = fm.axis_pt, w = line_w).unwrap();

            // Baseline (red)
            writeln!(typ, "  line((-1, 0), ({:.0}, 0), stroke: (paint: red, thickness: 0.8pt))", line_w).unwrap();

            // Descent (green dashed)
            writeln!(typ, "  line((-1, {d:.2}), ({w:.0}, {d:.2}), stroke: (paint: green.darken(20%).lighten(40%), thickness: 0.5pt, dash: \"dashed\"))",
                d = fm.descent_pt, w = line_w).unwrap();

            // The expression — single block, Typst handles all layout
            if font_preamble.is_empty() {
                writeln!(typ, "  content((0, 0), anchor: \"base-west\", text(size: {gts:.0}pt)[{expr}])").unwrap();
            } else {
                // Need to apply font show rule inline
                writeln!(typ, "  content((0, 0), anchor: \"base-west\", {{").unwrap();
                writeln!(typ, "    show math.equation: set text(font: \"{font_name}\")").unwrap();
                writeln!(typ, "    text(size: {gts:.0}pt)[{expr}]").unwrap();
                writeln!(typ, "  }})").unwrap();
            }

            writeln!(typ, "}})").unwrap();
        }

        writeln!(typ, "").unwrap();
    }

    // =======================================================================
    // Summary table
    // =======================================================================
    writeln!(typ, "== Baseline Detection Summary").unwrap();
    writeln!(typ, "").unwrap();
    writeln!(typ, "#table(").unwrap();
    writeln!(typ, "  columns: (auto, auto, auto, auto),").unwrap();
    writeln!(typ, "  stroke: 0.5pt, inset: 8pt,").unwrap();
    writeln!(typ, "  [*Expression*], [*Group?*], [*Baseline source*], [*y from top (pt)*],").unwrap();
    writeln!(typ, "  [$a + b$], [no], [text y-position], [{:.2}],", simple.items[0].2).unwrap();
    writeln!(typ, "  [$a_b$], [no], [largest text y], [{:.2}],", subscript.items[0].2).unwrap();
    writeln!(typ, "  [$frac(a, b)$], [no], [fallback ({:.0} + {:.2})], [{:.2}],",
        margin, metrics.ascent_pt, margin + metrics.ascent_pt).unwrap();
    writeln!(typ, "  [$lr([1 / q_(0)])$], [yes], [`frame.baseline()`], [{:.2}],",
        bracket.group_baseline.unwrap()).unwrap();
    writeln!(typ, ")").unwrap();

    // --- Write and compile ---
    let out_dir = format!(
        "{}/test-output",
        env!("CARGO_MANIFEST_DIR").replace("/crates/tip-core-typst", "")
    );
    std::fs::create_dir_all(&out_dir).ok();
    let typ_path = format!("{out_dir}/baseline-diagram.typ");
    let pdf_path = format!("{out_dir}/baseline-diagram.pdf");

    let mut f = std::fs::File::create(&typ_path).expect("create .typ");
    f.write_all(typ.as_bytes()).expect("write .typ");
    eprintln!("Wrote {typ_path}");

    let status = std::process::Command::new("typst")
        .args(["compile", "--font-path", &font_dir, &typ_path, &pdf_path])
        .status()
        .expect("failed to run typst");
    assert!(status.success(), "typst compile failed");
    eprintln!("Compiled {pdf_path}");
}
