[package]
name = "tip-core-typst"
version = "0.1.0"
edition = "2021"

[dependencies]
tip-protocol = { path = "../tip-protocol" }
typst = "0.15.0"
typst-layout = "0.15.0"
typst-svg = "0.15.0"
typst-kit = { version = "0.15.0", features = ["embedded-fonts", "scan-fonts", "system-downloader", "system-packages", "vendor-openssl"] }
typst-library = "0.15.0"
typst-utils = "0.15.0"
comemo = "0.4"
ecow = "0.2"
